-- Generated by scripts/schema_sql.py from bundestag-data-foundation src/bdf/db.py (SCHEMA). Do not edit by hand:
-- tests/test_schema.py fails when this file and the foundation drift apart.

CREATE TABLE IF NOT EXISTS person (
    id TEXT PRIMARY KEY,                -- Bundestag MdB id (MDB/ID == redner/@id)
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    name_prefix TEXT,                   -- Adel / Präfix ("von", "Freiherr von")
    academic_title TEXT,
    birth_date TEXT,                    -- ISO date
    birth_place TEXT,
    gender TEXT,
    party TEXT,
    is_mdb INTEGER NOT NULL DEFAULT 1,
    role TEXT,                          -- for non-MdB speakers: rolle_lang from the protocol
    dip_person_id TEXT,
    aw_politician_id INTEGER,
    wikidata_qid TEXT,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    fraction TEXT                       -- derived: the fraction in the newest Wahlperiode the person has a mandate in
                                        -- (the open membership, else the last one; without one, as for a Nachrücker
                                        -- not yet in the Stammdaten, the one printed in protocols and vote lists,
                                        -- else "fraktionslos"); NULL for everyone else
);

CREATE TABLE IF NOT EXISTS mandate (
    id TEXT PRIMARY KEY,                -- "<person_id>/<wp>"
    person_id TEXT NOT NULL REFERENCES person(id),
    wahlperiode INTEGER NOT NULL,
    from_date TEXT NOT NULL,
    to_date TEXT,
    mandate_type TEXT,                  -- Direktwahl | Landesliste
    constituency_number INTEGER,
    constituency_name TEXT,
    state TEXT,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS membership (
    id TEXT PRIMARY KEY,                -- "<person_id>/<wp>/<n>"
    person_id TEXT NOT NULL REFERENCES person(id),
    wahlperiode INTEGER NOT NULL,
    kind TEXT NOT NULL,                 -- fraction | committee | other
    name TEXT NOT NULL,                 -- normalised fraction, or institution name
    role TEXT,                          -- FKT_LANG, e.g. "Vorsitzende"
    from_date TEXT,
    to_date TEXT,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sitting (
    id TEXT PRIMARY KEY,                -- "21/94"
    wahlperiode INTEGER NOT NULL,
    number INTEGER NOT NULL,
    date TEXT NOT NULL,
    start_time TEXT,
    end_time TEXT,
    xml_url TEXT NOT NULL,
    pdf_url TEXT NOT NULL,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    preliminary INTEGER NOT NULL DEFAULT 0,  -- 1: the XML is the preliminary version ("Der gesamte und damit
                                        -- endgültige Stenografische Bericht … wird am … veröffentlicht"); it can
                                        -- lack the last pages. `update` re-fetches it until the final one is served
    final_announced TEXT,               -- the date the preliminary XML announces for the final version, ISO
    final_fetched_at TEXT,              -- retrieved_at of the XML once it is final; NULL while preliminary
    first_page INTEGER,                 -- Druckseite the XML's sitzungsverlauf starts on (start-seitennr)
    last_page INTEGER                   -- preliminary XML: the Druckseite its text ends on, found in the final PDF,
                                        -- which supplies the rest of the sitting (rows with the PDF as source_url);
                                        -- NULL for a final XML and while no PDF part could be read
);

CREATE TABLE IF NOT EXISTS agenda_item (
    id TEXT PRIMARY KEY,                -- "<sitting_id>/<position>"
    sitting_id TEXT NOT NULL REFERENCES sitting(id),
    position INTEGER NOT NULL,
    top_id TEXT NOT NULL,               -- XML top-id attribute, e.g. "Tagesordnungspunkt 3"
    title TEXT,
    drucksache_numbers TEXT NOT NULL,   -- JSON array of "21/7300"
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    no_debate INTEGER NOT NULL DEFAULT 0,  -- 1: the chair says no Aussprache is provided ("keine Aussprache
                                        -- vorgesehen")
    kind TEXT                           -- derived: befragung (Befragung der Bundesregierung) | fragestunde
                                        -- | aktuelle_stunde | NULL for every other item
);

CREATE TABLE IF NOT EXISTS agenda_sub_item (
    id TEXT PRIMARY KEY,                -- "<agenda_item_id>/<label>", e.g. "21/96/6/41b"
    agenda_item_id TEXT NOT NULL REFERENCES agenda_item(id),
    label TEXT NOT NULL,                -- as called up: "41b"; Zusatzpunkte "ZP8", "ZP1a"
    position INTEGER NOT NULL,          -- order within the agenda item
    title TEXT,                         -- this sub-item's title lines, joined with " | "
    drucksache_numbers TEXT NOT NULL,   -- JSON array of "21/7300", this sub-item's only
    first_paragraph INTEGER NOT NULL,   -- agenda_item_paragraph.position of the chair's call-up
    last_paragraph INTEGER NOT NULL,    -- … of the last paragraph before the next call-up (or the item's end)
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    no_debate INTEGER NOT NULL DEFAULT 0  -- 1: the chair says no Aussprache is provided (for the block or this item)
);

CREATE TABLE IF NOT EXISTS agenda_item_vorlage (
    id TEXT PRIMARY KEY,                -- "<agenda_item_id or sub_item_id>/<drucksache_number>"
    agenda_item_id TEXT NOT NULL REFERENCES agenda_item(id),
    sub_item_id TEXT REFERENCES agenda_sub_item(id),  -- set for the Drucksachen of a sub-item, NULL otherwise
    drucksache_number TEXT NOT NULL,    -- "21/7300"
    vorgang_id TEXT REFERENCES vorgang(id),  -- the only Vorgang of that Drucksache in vorgang_drucksache; else NULL
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    via TEXT NOT NULL DEFAULT 'title'   -- title: the item's printed title names it; decision: a decision taken under
                                        -- the item names it (an Entschließungsantrag decided after the bill)
);

CREATE TABLE IF NOT EXISTS speech (
    id TEXT PRIMARY KEY,                -- XML rede/@id, "-2", "-3" … when split; Fragestunde:
                                        -- "<agenda_item_id>/f<n>" (synthetic, docs/decisions.md)
    sitting_id TEXT NOT NULL REFERENCES sitting(id),
    agenda_item_id TEXT REFERENCES agenda_item(id),
    position INTEGER NOT NULL,          -- order within the sitting
    person_id TEXT NOT NULL REFERENCES person(id),
    speaker_name TEXT NOT NULL,
    speaker_role TEXT,
    fraction TEXT,
    text TEXT NOT NULL,                 -- clean text: paragraphs of kind 'text', blank-line joined
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'rede',  -- rede | fragestunde: a Fragestunde question, answer or
                                        -- Nachfrage; shown, but left out of speech counts and shares
    sub_item_id TEXT REFERENCES agenda_sub_item(id),  -- the sub-item of a block item during which the speech was
                                        -- given (its call-up is the last one before the speech), else NULL
    speaker_group TEXT,                 -- derived: who the speech counts for: a fraction | Bundesregierung (given in a
                                        -- federal government office, whatever the speaker's fraction) | Bundesrat
                                        -- (a Land office) | Sonstige
    member_fraction TEXT,               -- derived: the speaker's fraction on the sitting day (membership, else the
                                        -- printed one), also when speaking as a minister; NULL for non-members
    rede_id TEXT,                       -- derived: the speech this part belongs to (id without "-2", "-3" …)
    interruption TEXT,                  -- derived: zwischenfrage | kurzintervention for a part by someone other than
                                        -- the rede's first speaker (docs/design.md "Speech parts"); NULL otherwise
    interruption_start TEXT             -- derived: the first part of the interruption this part belongs to (a question
                                        -- over two parts is one interruption); NULL with interruption
);

CREATE TABLE IF NOT EXISTS speech_paragraph (
    id TEXT PRIMARY KEY,                -- "<speech_id>/<position>"
    speech_id TEXT NOT NULL REFERENCES speech(id),
    position INTEGER NOT NULL,
    kind TEXT NOT NULL,                 -- text | comment | chair | procedural
    text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS interjection (
    id TEXT PRIMARY KEY,                -- "<speech_id>/<paragraph>/<part>/<actor>"
    speech_id TEXT NOT NULL REFERENCES speech(id),
    paragraph INTEGER NOT NULL,         -- speech_paragraph.position of the comment
    part INTEGER NOT NULL,              -- order of the part within the comment
    kind TEXT NOT NULL,                 -- beifall | zuruf | gegenruf | lachen | heiterkeit | widerspruch
                                        -- | zustimmung | unruhe | other
    actor TEXT NOT NULL,                -- fraction | members (some of the fraction) | person | house | unknown
    fraction TEXT,
    person_id TEXT REFERENCES person(id),
    name TEXT,                          -- printed name of a person
    text TEXT,                          -- the words of a Zuruf / Gegenruf, when printed
    to_person_id TEXT REFERENCES person(id),  -- addressee named in the comment ("an den Abg. …");
    to_name TEXT                        -- NULL: aimed at the speaker of speech_id
);

CREATE TABLE IF NOT EXISTS drucksache (
    id TEXT PRIMARY KEY,                -- DIP id
    number TEXT NOT NULL,               -- "21/7300"
    wahlperiode INTEGER NOT NULL,
    type TEXT,                          -- drucksachetyp
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    pdf_url TEXT,
    publisher TEXT,                     -- herausgeber: BT | BR
    originators TEXT NOT NULL,          -- JSON array of urheber titles
    author_count INTEGER,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    originator_groups TEXT              -- derived: JSON array of the fractions and "Bundesregierung" among the
                                        -- originators (a ministry counts as the Bundesregierung); [] for none
);

CREATE TABLE IF NOT EXISTS drucksache_author (
    id TEXT PRIMARY KEY,                -- "<drucksache_id>/<dip_person_id>"
    drucksache_id TEXT NOT NULL REFERENCES drucksache(id),
    dip_person_id TEXT NOT NULL,
    person_id TEXT REFERENCES person(id),
    name TEXT NOT NULL,
    activity_type TEXT,                 -- aktivitaetsart, e.g. "Antrag", "Kleine Anfrage"
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS question_activity (
    id TEXT PRIMARY KEY,                -- DIP Aktivität id
    vorgang_id TEXT NOT NULL,           -- the single question (DIP vorgangsbezug), a Vorgang of question_type
    question_type TEXT NOT NULL,        -- Schriftliche Frage | Mündliche Frage
    activity_type TEXT NOT NULL,        -- Frage | Zusatzfrage | Antwort
    dip_person_id TEXT NOT NULL,
    person_id TEXT REFERENCES person(id),
    name TEXT NOT NULL,                 -- DIP's title, "Julia Schneider, MdB, BÜNDNIS 90/DIE GRÜNEN"
    ressort TEXT,                       -- Antwort: the answering ministry as the title names it, else NULL
    document_kind TEXT NOT NULL,        -- Drucksache (the Sammeldrucksache) | Plenarprotokoll
    document_number TEXT NOT NULL,      -- "21/4372", "21/9"
    question_numbers TEXT,              -- Drucksache: DIP's frage_nummer, "93, 94"
    page TEXT,                          -- Plenarprotokoll: page and quadrant, "683D"
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS question_turn (
    speech_id TEXT PRIMARY KEY REFERENCES speech(id),
    role TEXT NOT NULL,                 -- einleitung | frage | antwort | nachfrage (the asker's) | zusatzfrage
                                        -- (another member's), as the presidency calls the turn (docs/design.md
                                        -- "Question turns")
    thread_id TEXT REFERENCES speech(id),  -- the question the turn belongs to: Befragung: its frage (a frage's own
                                        -- id), NULL for an einleitung; Fragestunde: the first turn after the call
    vorgang_id TEXT REFERENCES vorgang(id)  -- Fragestunde: the DIP Mündliche Frage (NULL until matched); NULL in the
                                        -- Befragung
);

CREATE TABLE IF NOT EXISTS question_text (
    id TEXT PRIMARY KEY,                -- "<drucksache_number>/<number>/<part>", "21/1949/6/frage"
    vorgang_id TEXT REFERENCES vorgang(id),  -- the DIP Vorgang of the question (NULL until matched)
    drucksache_number TEXT NOT NULL,    -- the Drucksache listing the question: Mündliche Fragen: the Fragen-Drucksache
    drucksache_id TEXT REFERENCES drucksache(id),  -- its DIP id (NULL when not fetched)
    position INTEGER NOT NULL,          -- order within the source document
    part TEXT NOT NULL,                 -- vorbemerkung_fragesteller | frage | vorbemerkung_bundesregierung | antwort |
                                        -- anlage (docs/design.md "Question texts")
    number TEXT,                        -- the question's number in the Drucksache, "6", "3a"; an annex's; NULL for a
                                        -- preliminary remark
    text TEXT NOT NULL,                 -- paragraphs joined by blank lines; tables are in question_table
    name TEXT,                          -- as printed: the asker (frage), the answerer with office (antwort); the
                                        -- ministry (answers to Anfragen)
    answerer_person_id TEXT REFERENCES person(id),  -- antwort: the answerer (from DIP; NULL until matched)
    answer_date TEXT,                   -- antwort: the date of the document printing the answer
    thread_id TEXT REFERENCES speech(id),  -- a question answered in the Fragestunde: its first turn (question_turn)
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS question_table (
    id TEXT PRIMARY KEY,                -- "<question_text_id>/<k>"
    question_text_id TEXT NOT NULL REFERENCES question_text(id),
    position INTEGER NOT NULL,          -- k: order among the text's tables
    after_paragraph INTEGER NOT NULL,   -- how many of the text's paragraphs come before the table
    cells TEXT NOT NULL                 -- JSON {"caption", "head", "body", "foot"}: rows of cells, a cell its text
                                        -- or {"text", "colspan", "rowspan"}; a table without ruling, whose cells are
                                        -- not read: {"extracted": false, "page": <page of the PDF>}
);

CREATE TABLE IF NOT EXISTS question_parse (
    vorgang_id TEXT PRIMARY KEY REFERENCES vorgang(id),
    status TEXT NOT NULL,               -- complete | partial | unanswered | failed (docs/design.md "Question texts")
    questions INTEGER NOT NULL,         -- the questions read
    answered INTEGER NOT NULL,          -- … of them with an answer (written or spoken)
    source_document_id TEXT             -- the document read: "BT-Drs. 21/1095", "BT-PlPr. 21/30"; NULL: none yet
);

CREATE TABLE IF NOT EXISTS vorgang (
    id TEXT PRIMARY KEY,                -- DIP id
    wahlperiode INTEGER NOT NULL,
    type TEXT,
    title TEXT NOT NULL,
    status TEXT,                        -- beratungsstand
    subjects TEXT NOT NULL,             -- JSON array (sachgebiet)
    initiators TEXT NOT NULL,           -- JSON array (initiative)
    verkuendung TEXT,                   -- JSON array of DIP verkuendung objects (BGBl reference), NULL if none
    inkrafttreten TEXT,                 -- JSON array of {datum, erlaeuterung} objects, NULL if none
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vorgang_drucksache (
    vorgang_id TEXT NOT NULL REFERENCES vorgang(id),
    drucksache_id TEXT NOT NULL REFERENCES drucksache(id),
    PRIMARY KEY (vorgang_id, drucksache_id)
);

CREATE TABLE IF NOT EXISTS vorgang_position (
    id TEXT PRIMARY KEY,                -- DIP id of the Vorgangsposition (one step of a Vorgang)
    vorgang_id TEXT NOT NULL,           -- DIP id of the Vorgang; not every Vorgang is in table vorgang
    date TEXT NOT NULL,                 -- datum
    position TEXT NOT NULL,             -- vorgangsposition, e.g. "Gesetzentwurf", "1. Beratung", "Antwort"
    chamber TEXT,                       -- zuordnung: BT | BR | BV | …
    document_kind TEXT,                 -- fundstelle.dokumentart: Drucksache | Plenarprotokoll
    document_number TEXT,               -- fundstelle.dokumentnummer: "21/304" (Drucksache), "21/13" (protocol)
    document_type TEXT,                 -- fundstelle.drucksachetyp
    pdf_url TEXT,                       -- fundstelle.pdf_url
    pages TEXT,                         -- "1234-1236" (fundstelle.anfangsseite-endseite), protocols only
    originators TEXT NOT NULL,          -- JSON array of urheber titles
    ressort TEXT,                       -- JSON array of objects {titel, federfuehrend}, NULL if none
    decisions TEXT,                     -- JSON array of beschlussfassung objects as in DIP, NULL if none
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vorgang_referral (
    position_id TEXT NOT NULL REFERENCES vorgang_position(id),
    vorgang_id TEXT NOT NULL,           -- DIP id of the Vorgang (as vorgang_position.vorgang_id)
    committee TEXT NOT NULL,            -- ueberweisung.ausschuss as DIP names it, not matched to membership names
    committee_short TEXT,               -- ueberweisung.ausschuss_kuerzel, e.g. "EU"; NULL if DIP gives none
    lead INTEGER NOT NULL,              -- 1 = federführend (ueberweisung.federfuehrung), 0 = mitberatend
    kind TEXT,                          -- ueberweisung.ueberweisungsart, NULL if DIP gives none
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    PRIMARY KEY (position_id, committee)
);

CREATE TABLE IF NOT EXISTS roll_call_vote (
    id TEXT PRIMARY KEY,                -- "21/90/7"
    sitting_id TEXT REFERENCES sitting(id),
    number INTEGER NOT NULL,            -- Abstimmnr
    date TEXT NOT NULL,
    title TEXT NOT NULL,
    drucksache_number TEXT,
    vorgang_id TEXT REFERENCES vorgang(id),
    link_method TEXT,                   -- dip_beschluss | title_regex | manual
    yes INTEGER NOT NULL,
    no INTEGER NOT NULL,
    abstain INTEGER NOT NULL,
    invalid INTEGER NOT NULL,
    absent INTEGER NOT NULL,
    xlsx_url TEXT NOT NULL,
    pdf_url TEXT,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    agenda_item_id TEXT REFERENCES agenda_item(id)  -- same sitting: Drucksache on the agenda, else the decision's
);

CREATE TABLE IF NOT EXISTS individual_vote (
    id TEXT PRIMARY KEY,                -- "<vote_id>/<row>"
    vote_id TEXT NOT NULL REFERENCES roll_call_vote(id),
    person_id TEXT REFERENCES person(id),
    last_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    fraction TEXT NOT NULL,
    vote TEXT NOT NULL                  -- yes | no | abstain | invalid | absent
);

CREATE TABLE IF NOT EXISTS aw_profile (
    aw_politician_id INTEGER PRIMARY KEY,
    person_id TEXT REFERENCES person(id),
    url TEXT NOT NULL,                  -- the public profile page
    questions INTEGER,                  -- citizen questions on the profile, all periods (statistic_questions)
    questions_answered INTEGER,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS side_job (
    id INTEGER PRIMARY KEY,             -- abgeordnetenwatch sidejob id
    wahlperiode INTEGER NOT NULL,
    person_id TEXT REFERENCES person(id), -- via aw mandate -> politician; NULL if the politician is unmatched
    aw_mandate_id INTEGER NOT NULL,
    label TEXT NOT NULL,                -- the entry as published, e.g. "Mitglied des Beirates, ehrenamtlich (ab …)"
    job_title_extra TEXT,
    category TEXT,                      -- Bundestag category (Verhaltensregeln), label of aw's code
    income_level INTEGER,               -- published Stufe 0..10; NULL: none published
    income_range TEXT,                  -- the Stufe's range, e.g. "1.000 € bis 3.500 €"
    income REAL,                        -- amount as published by aw (`income`); NULL if none
    interval TEXT,                      -- einmalig | monatlich | jährlich
    additional_information TEXT,        -- aw's free text (may contain HTML)
    organization_id INTEGER,            -- aw sidejob_organization id
    organization TEXT,
    city TEXT,
    topics TEXT,                        -- JSON list of aw topic labels
    created TEXT,                       -- date first recorded by aw
    data_change_date TEXT,              -- date aw last changed the record
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS constituency (
    id TEXT PRIMARY KEY,                -- "<election>/<number>", e.g. "btw25/114"
    election TEXT NOT NULL,             -- "btw25"
    number INTEGER NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,                -- Land abbreviation, as mandate.state
    seat_party TEXT,                    -- party whose candidate got the seat; NULL: no Zweitstimmendeckung
    electorate INTEGER,
    voters INTEGER,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS constituency_result (
    id TEXT PRIMARY KEY,                -- "<election>/<number>/<group order>/<vote>"
    election TEXT NOT NULL,
    constituency_number INTEGER NOT NULL,
    group_kind TEXT NOT NULL,           -- party | individual (Einzelbewerber)
    party TEXT NOT NULL,                -- Gruppenname, e.g. "SPD", "CSU", "GRÜNE"
    vote INTEGER NOT NULL,              -- 1 = Erststimme, 2 = Zweitstimme
    votes INTEGER NOT NULL,
    percent REAL,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS party_fraction (
    party TEXT PRIMARY KEY,             -- as person.party or the Bundeswahlleiterin print it: "CSU", "GRÜNE"
    fraction TEXT NOT NULL              -- the fraction its members sit in: "CDU/CSU", "BÜNDNIS 90/DIE GRÜNEN"
);

CREATE TABLE IF NOT EXISTS constituency_municipality (
    id TEXT PRIMARY KEY,                -- "<election>/<ags>/<constituency number>", e.g. "btw25/02000000/18"
    election TEXT NOT NULL,
    ags TEXT NOT NULL,                  -- Amtlicher Gemeindeschlüssel, 8 digits
    name TEXT NOT NULL,                 -- Gemeindename as in the file, e.g. "Flensburg, Stadt"
    district TEXT NOT NULL,             -- Kreisname, tells the many "Neustadt" apart
    state TEXT NOT NULL,                -- Land abbreviation, as constituency.state
    constituency_number INTEGER NOT NULL,
    split INTEGER NOT NULL,             -- 1: the Gemeinde is split across Wahlkreise, one row per Wahlkreis
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS election_candidacy (
    id TEXT PRIMARY KEY,                -- "<election>/<row in the Gewählte file>"
    election TEXT NOT NULL,
    person_id TEXT REFERENCES person(id),
    last_name TEXT NOT NULL,
    first_names TEXT NOT NULL,
    birth_year INTEGER,
    party TEXT NOT NULL,
    elected_via TEXT NOT NULL,          -- constituency | list
    constituency_number INTEGER,        -- won there, or stood there (list members)
    first_vote_percent REAL,            -- constituency winners only; others: constituency_result
    list_state TEXT,
    list_position INTEGER,
    occupation TEXT,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mandate_successor (
    id TEXT PRIMARY KEY,                -- "<election>/<Bek.-Nr.>", the list's running number
    election TEXT NOT NULL,
    predecessor_person_id TEXT REFERENCES person(id),
    predecessor_name TEXT NOT NULL,     -- as printed, "Heveling, Ansgar Guido Karl Johannes"
    predecessor_party TEXT NOT NULL,
    predecessor_state TEXT NOT NULL,    -- Land code as in mandate.state ("NW")
    predecessor_seat TEXT NOT NULL,     -- "LL 003" (Landesliste, position) | "WK 044" (Wahlkreis)
    reason TEXT NOT NULL,               -- Ausscheidungsgrund: Ablehnung, Mandatsverzicht, Tod, …
    person_id TEXT REFERENCES person(id),
    name TEXT NOT NULL,                 -- the successor as printed, "Breilmann, Michael"
    birth_year INTEGER NOT NULL,
    party TEXT NOT NULL,
    state TEXT NOT NULL,                -- the Land whose Landesliste the seat comes from
    seat TEXT NOT NULL,                 -- the successor's candidacy, "LL 018" | "WK 282"
    from_date TEXT NOT NULL,            -- Beginn der Mitgliedschaft
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS person_alias (
    alias_id TEXT PRIMARY KEY,          -- a placeholder person id that is gone: a Wikidata QID ("Q109023") made for a
                                        -- government member, or "pdf-<name>" for a speaker read from a PDF
    person_id TEXT NOT NULL REFERENCES person(id),  -- the person it turned out to be
    recorded_at TEXT NOT NULL           -- when the ingest first retired the placeholder, ISO timestamp
);

CREATE TABLE IF NOT EXISTS person_photo (
    person_id TEXT PRIMARY KEY REFERENCES person(id),
    image_url TEXT NOT NULL,            -- the image as downloaded (bundestag.de rendition or Commons thumbnail)
    credit TEXT,                        -- photographer / rights holder as printed by the source, without "©"
    bio_url TEXT,                       -- bundestag.de biography page; NULL for Commons portraits
    local_path TEXT NOT NULL,           -- the unchanged download, relative to data/raw/
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS government_role (
    id TEXT PRIMARY KEY,                -- wikidata: statement id of the "position held" (P39) claim;
                                        -- else "<source_kind>:<person_id>:<kind>:<department key>"
    person_id TEXT REFERENCES person(id),
    wikidata_qid TEXT,                  -- the holder's QID, when known
    name TEXT NOT NULL,                 -- the holder's Wikidata label, else first + last name of the person
    office TEXT NOT NULL,               -- Wikidata's position label, else a generic one, "Bundesminister der Finanzen"
    department TEXT,                    -- ministry or office, "Bundesministerium der Finanzen"
    kind TEXT NOT NULL,                 -- kanzler | minister | staatsminister | parl_sts | beamteter_sts
    from_date TEXT NOT NULL,            -- wikidata, stammdaten: start of office; protocol: first sitting that
                                        -- prints the role for the person (evidence, not the appointment)
    to_date TEXT,                       -- wikidata, stammdaten: end of office (or inferred, docs/decisions.md);
                                        -- protocol: last sitting that prints the role (evidence, not the end)
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    source_kind TEXT NOT NULL DEFAULT 'wikidata'  -- wikidata | stammdaten | protocol: source of dates + provenance
);

CREATE TABLE IF NOT EXISTS agenda_item_paragraph (
    id TEXT PRIMARY KEY,                -- "<agenda_item_id>/<position>"
    agenda_item_id TEXT NOT NULL REFERENCES agenda_item(id),
    position INTEGER NOT NULL,
    kind TEXT NOT NULL,                 -- chair | comment | procedural | speaker | text
    text TEXT NOT NULL,
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS decision (
    id TEXT PRIMARY KEY,                -- roll-call: roll_call_vote.id ("21/90/7", else "21/90/n<k>");
                                        -- show of hands: "<sitting_id>/h<n>"
    sitting_id TEXT NOT NULL REFERENCES sitting(id),
    agenda_item_id TEXT REFERENCES agenda_item(id),
    n INTEGER NOT NULL,                 -- running number per kind within the sitting
    position INTEGER NOT NULL,          -- order among all decisions of the sitting
    kind TEXT NOT NULL,                 -- namentlich | handzeichen
    subject TEXT NOT NULL,
    drucksache_number TEXT,
    result TEXT,                        -- angenommen | abgelehnt | NULL (not found)
    roll_call_vote_id TEXT REFERENCES roll_call_vote(id),
    text TEXT NOT NULL,                 -- the chair's words the decision was read from
    source_url TEXT NOT NULL, source_document_id TEXT NOT NULL, retrieved_at TEXT NOT NULL,
    sub_item_id TEXT REFERENCES agenda_sub_item(id),  -- the block item the chair had called up last, else NULL
    vorgang_id TEXT REFERENCES vorgang(id),  -- the decision's only Vorgang in decision_vorgang, else NULL
    dip_position_id TEXT,               -- the DIP Vorgangsposition (BT, this sitting's Plenarprotokoll) whose
                                        -- beschlussfassung names the decision's Drucksache, when exactly one does
    dip_result TEXT                     -- that beschlussfassung's beschlusstenor, "Annahme der Vorlage"
);

CREATE TABLE IF NOT EXISTS decision_vorgang (
    decision_id TEXT NOT NULL REFERENCES decision(id),
    vorgang_id TEXT NOT NULL REFERENCES vorgang(id),
    via TEXT NOT NULL,                  -- roll_call: the roll call's Vorgang (DIP's Namentliche Abstimmung) |
                                        -- dip_step: DIP's step in this sitting deciding the Drucksache |
                                        -- drucksache: a Vorgang of the decision's or roll call's Drucksache |
                                        -- agenda_item: the single Vorgang of its (sub-)item's Vorlagen, for a
                                        -- decision whose Drucksache the chair does not name
    PRIMARY KEY (decision_id, vorgang_id)
);

CREATE TABLE IF NOT EXISTS decision_fraction (
    decision_id TEXT NOT NULL REFERENCES decision(id),
    fraction TEXT NOT NULL,             -- normalised, as membership.name
    position TEXT NOT NULL,             -- yes | no | abstain
    PRIMARY KEY (decision_id, fraction)
);

CREATE INDEX IF NOT EXISTS speech_person ON speech(person_id);
CREATE INDEX IF NOT EXISTS agenda_paragraph_item ON agenda_item_paragraph(agenda_item_id);
CREATE INDEX IF NOT EXISTS decision_sitting ON decision(sitting_id);
CREATE INDEX IF NOT EXISTS decision_agenda_item ON decision(agenda_item_id);
CREATE INDEX IF NOT EXISTS agenda_sub_item_item ON agenda_sub_item(agenda_item_id);
CREATE INDEX IF NOT EXISTS vorlage_item ON agenda_item_vorlage(agenda_item_id);
CREATE INDEX IF NOT EXISTS vorlage_drucksache ON agenda_item_vorlage(drucksache_number);
CREATE INDEX IF NOT EXISTS speech_sitting ON speech(sitting_id);
CREATE INDEX IF NOT EXISTS paragraph_speech ON speech_paragraph(speech_id);
CREATE INDEX IF NOT EXISTS vote_person ON individual_vote(person_id);
CREATE INDEX IF NOT EXISTS interjection_speech ON interjection(speech_id);
CREATE INDEX IF NOT EXISTS interjection_person ON interjection(person_id);
CREATE INDEX IF NOT EXISTS vote_vote ON individual_vote(vote_id);
CREATE INDEX IF NOT EXISTS author_person ON drucksache_author(person_id);
CREATE INDEX IF NOT EXISTS author_dip_person ON drucksache_author(dip_person_id);
CREATE INDEX IF NOT EXISTS question_vorgang ON question_activity(vorgang_id);
CREATE INDEX IF NOT EXISTS question_person ON question_activity(person_id);
CREATE INDEX IF NOT EXISTS question_turn_thread ON question_turn(thread_id);
CREATE INDEX IF NOT EXISTS question_text_vorgang ON question_text(vorgang_id);
CREATE INDEX IF NOT EXISTS question_text_document ON question_text(source_document_id);
CREATE INDEX IF NOT EXISTS question_table_text ON question_table(question_text_id);
CREATE INDEX IF NOT EXISTS drucksache_date ON drucksache(date);
CREATE INDEX IF NOT EXISTS person_dip ON person(dip_person_id);
CREATE INDEX IF NOT EXISTS vorgang_position_vorgang ON vorgang_position(vorgang_id);
CREATE INDEX IF NOT EXISTS decision_vorgang_vorgang ON decision_vorgang(vorgang_id);
CREATE INDEX IF NOT EXISTS vorgang_position_date ON vorgang_position(date);
CREATE INDEX IF NOT EXISTS vorgang_referral_vorgang ON vorgang_referral(vorgang_id);
CREATE INDEX IF NOT EXISTS candidacy_person ON election_candidacy(person_id);
CREATE INDEX IF NOT EXISTS municipality_constituency ON constituency_municipality(election, constituency_number);
CREATE INDEX IF NOT EXISTS government_role_person ON government_role(person_id);
