"""Write tests/schema.sql from the foundation's SCHEMA, so the test store has exactly the foundation's tables.

    uv run python scripts/schema_sql.py [path/to/bundestag-data-foundation]

The foundation checkout defaults to ../bundestag-data-foundation (or $BDF_REPO). tests/test_schema.py fails when
the committed file and the foundation's SCHEMA drift apart; run this script and commit the result.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "tests" / "schema.sql"
HEADER = """\
-- Generated by scripts/schema_sql.py from bundestag-data-foundation src/bdf/db.py (SCHEMA). Do not edit by hand:
-- tests/test_schema.py fails when this file and the foundation drift apart.
"""


def foundation_repo(arg: str | None = None) -> Path:
    return Path(arg or os.environ.get("BDF_REPO") or ROOT.parent / "bundestag-data-foundation")


def load_schema(repo: Path) -> str:
    """The foundation's SCHEMA string; db.py needs only the standard library, so it is loaded straight from file."""
    path = repo / "src" / "bdf" / "db.py"
    spec = importlib.util.spec_from_file_location("_bdf_db", path)
    if spec is None or spec.loader is None:
        raise FileNotFoundError(path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.SCHEMA


def render(schema: str) -> str:
    return HEADER + "\n" + schema.strip() + "\n"


def main(argv: list[str]) -> None:
    repo = foundation_repo(argv[0] if argv else None)
    TARGET.write_text(render(load_schema(repo)), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} from {repo}")


if __name__ == "__main__":
    main(sys.argv[1:])
